apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - image: <image_placeholder>
          imagePullPolicy: Always
          name: sample-app
          ports:
            - containerPort: 8080
      restartPolicy: Always
